# Generated by Django 3.2.6 on 2021-09-28 01:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='InformacionUsuarios',
            new_name='InfoUser',
        ),
    ]
